matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
      language: node_js
      osx_image: xcode9.0
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: xenial
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      before_install:
        - sudo apt-get install -y libudev-dev rpm
      addons:
        apt:
          update: true

    - os: windows
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder'
      before_install:
        - ./win.sh


before_install: yarn install --network-timeout 1000000

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"

install:
  - yarn --ignore-engines

script:
  - yarn package-ci
