sudo: true

language: node_js

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      compiler:
        - clang
        - gcc
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

install:
  - yarn
  - cd app && yarn

script:
  - yarn package
